version: '3.9'
services:
  backend:
    build: .
    environment:
      - PORT=3000
      - JWT_SECRET=catinboardwritekmkmoc1o4lf4mx4kcmk3ol
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=nest2fa
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
    depends_on:
      - db
    ports:
      - '3000:3000'

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest2fa
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: